In [1]:
import pandas as pd

In [7]:
# read in files
amenities = pd.read_csv("data\All_amenities_presence_absence.csv")
listings = pd.read_csv("data\listings.csv")
booking_ratios = pd.read_csv("data\listing_booking_info.csv")

In [8]:
# merge amenities, booking info, and amenity counts
merged_data = pd.merge(listings,booking_ratios,left_on='id', right_on='listing_id')
amenities_selected = amenities[['id', 'total_amenities','Unnamed: 0']]
merged_data = pd.merge(merged_data, amenities_selected, on='id', how='left')

merged_data.head()

     id                        listing_url       scrape_id last_scraped  ... available_days booking_ratio total_amenities Unnamed: 0_y
0  2595  https://www.airbnb.com/rooms/2595  20241104040953   2024-11-04  ...            365      0.000000              32            0
1  6848  https://www.airbnb.com/rooms/6848  20241104040953   2024-11-04  ...            185      0.493151              26            1
2  6872  https://www.airbnb.com/rooms/6872  20241104040953   2024-11-04  ...             83      0.772603              18            2
3  6990  https://www.airbnb.com/rooms/6990  20241104040953   2024-11-04  ...            284      0.221918              19            3
4  7064  https://www.airbnb.com/rooms/7064  20241104040953   2024-11-04  ...              0      1.000000              15            4

[5 rows x 83 columns]

In [9]:
# remove unnecessary columns 
merged_data = merged_data.drop(columns=['listing_url','scrape_id','last_scraped','source','name','description','neighborhood_overview','picture_url','host_id',
    'host_url','host_name','host_since','host_location','host_about','host_thumbnail_url','host_picture_url','host_neighbourhood','host_listings_count','host_total_listings_count',
    'host_verifications','neighbourhood','neighbourhood_group_cleansed','latitude','longitude','amenities','minimum_minimum_nights','maximum_maximum_nights','minimum_maximum_nights',
    'maximum_maximum_nights','minimum_nights_avg_ntm','maximum_nights_avg_ntm','calendar_updated','has_availability','availability_30','availability_60','availability_90',
    'availability_365','calendar_last_scraped','number_of_reviews','number_of_reviews_ltm','number_of_reviews_l30d','first_review','last_review','calculated_host_listings_count',
    'calculated_host_listings_count_entire_homes','calculated_host_listings_count_private_rooms','calculated_host_listings_count_shared_rooms','reviews_per_month','review_scores_accuracy'])
merged_data.head()

merged_data = merged_data.drop(columns=['total_days','unavailable_days','available_days'])

merged_data = merged_data.dropna() 
merged_data = merged_data.drop(columns=['listing_id','id','Unnamed: 0_x','license','Unnamed: 0_y'])

#remove any lingering listings withh more than 70% booking ratio (invalid listings)
merged_data = merged_data[(merged_data['booking_ratio'] <= 0.70)]

merged_data['price'] = merged_data['price'].replace({'\\$': '', ',': ''}, regex=True)
merged_data['price'] = pd.to_numeric(merged_data['price'], errors='coerce')

merged_data['host_response_rate'] = merged_data['host_response_rate'].replace({'\\%': '', ',': ''}, regex=True)
merged_data['host_response_rate'] = pd.to_numeric(merged_data['host_response_rate'], errors='coerce')

merged_data['host_acceptance_rate'] = merged_data['host_acceptance_rate'].replace({'\\%': '', ',': ''}, regex=True)
merged_data['host_acceptance_rate'] = pd.to_numeric(merged_data['host_acceptance_rate'], errors='coerce')


merged_data.head()

    host_response_time  host_response_rate  host_acceptance_rate  ... instant_bookable booking_ratio total_amenities
5       within an hour                 100                   100  ...                t      0.410959              51
18      within an hour                 100                   100  ...                f      0.619178              39
39      within an hour                 100                   100  ...                t      0.649315              58
43      within an hour                 100                   100  ...                t      0.161644              32
49  within a few hours                 100                    50  ...                f      0.030137              69

[5 rows x 27 columns]

In [ ]:
#write out csv
#merged_data.to_csv("Combined_data_v1.csv")